spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/muke?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2b8
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  context-path: /sell

wechat:
  mpAppId: wxec078a891c5d68e8
  mpAppSecret: 556e71b77685ee93ee1427bd08c4916d
  notifyUrl: http://yyymeishaonv.natapp1.cc/sell/pay/notify