spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.31.30/dbsell?characterEncoding=utf-8&userSSL=false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  context-path: /sell