spring:
  profiles:
    active: home
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.31.30
    port: 6379

wechat:
  mpAppId: wxa6344813f106bc7a
  mpAppSecret: 0561d7c09b9cc71b0083e9133e9a903d
  openAppId : wxaf53a107603fccae
  openAppSecret : 4ca3a5a3fb96f41ff47ec0e65c88e4ce
  mchId: 137945590x
  mchKey: 0561d7c09b9cc71b00xxxxxxxxxxxx
  keyPath: D:/weixin_cert/apiclient_cert.p12
  notify_url: http://gzcstec.com/sell/pay/notify
  templateIds:
    orderStatus: uyjvfWUNNxavK_hW_dfNM1noVp-jHXcjadjBcM8BVYY

projectUrlConfig:
  mpAuthorizeUrl: http://fmx.weixin.gzcstec.com
  openAuthorizeUrl: http://fmx.weixin.gzcstec.com
  sell: http://fmx.weixin.gzcstec.com
mybatis:
  mapper-locations: classpath:mapper/*.xml


